### ISSUE TITLE
About potential labels appears in the dataset

### ISSUE THREAD

**Issue by tianrenZ0725** [LL-a-VO/LLaVO#2]
Hi team

Recently my friend and I are reading your paper. We have noticed that in your provided text datasets, words of potential labels appeared in either Tags, Attributes or Captions. We raised a concern that the LLM may exposed to a label leakage situation where the classification results are directly correlated to sample variable(potential label). I am wondering what is the opinion regarding to this issue?

Many thanks
![image](https://github.com/LL-a-VO/LLaVO/assets/43900439/db0413aa-7880-4534-b123-7091c7e30ec6)

**Comment by shuhao02** [comment]
Sorry for the delay of my response.

I understand your concern that the LLM potentially taking a shortcut and only relying on the label word for recognition. While the label word may indeed have an influence on the classification result, it does not have absolute control over it. In Example 3-7 provided in the appendix, it is evident that the LLM focuses not only on the label word but also on other words that assist in the classification process.

Furthermore, there are cases where certain textual descriptions either lack any label words or contain multiple different label words, yet the LLM is still capable of classifying them correctly.
